#!/bin/bash

mkdir -p /etc/nginx/sites-available
rm -f -R /etc/nginx/sites-enabled
mkdir -p /etc/nginx/sites-enabled
mkdir -p /etc/nginx/snippets
cp redteam /etc/nginx/sites-available/redteam

rm /etc/nginx/conf.d/ -r
mkdir /etc/nginx/conf.d
cp redteam /etc/nginx/conf.d/redteam.conf

ln -f -s /etc/nginx/sites-available/redteam /etc/nginx/sites-enabled/

cp self-signed.conf /etc/nginx/snippets/self-signed.conf
cp ssl-params.conf /etc/nginx/snippets/ssl-params.conf
